id: d32cad04-30b1-4790-a390-0b5f14724243
name: Mi Primer Bitcoin
links:
  website: https://miprimerbitcoin.io/
  twitter: https://twitter.com/MyfirstBitcoin_
  nostr: npub17cyatz6z2dzcw6xehtcm9z45m76lde5smxdmyasvs00r4pqv863qrs4ml3

  tags:
    - bitcoin-only
    - education

category: education

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.32
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.11
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.32
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.43
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.32
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.43
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.38
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.38
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.32

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.32
tags:
  - adoption
  - user-friendly
