id: 3b28b0f4-4a6f-4fb1-97be-0ae28c8fdb1c
name: Bitcoin Rodeo
category: conference

links:
  website: https://bitcoinrodeo.com/
  twitter: https://x.com/TheBitcoinRodeo

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-19
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.05
tags:
  - historical
  - market-trends
  - case-studies
contributor_names:
  - PaoloFoti
