id: d047bf01-6b1c-4fcb-92ec-84f20305b47e
name: Node Nation
links:
  twitter: https://x.com/NodeNationSV_

category: education

# Proofreading metadata
original_language: en
proofreading:
  - language: en
    last_contribution_date: 2024-08-31
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.1

  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.31

  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21

  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.26

  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.31

  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.31

  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21

  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.36

  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.26

  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.42

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.31

  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21

  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.31

  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.42

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.36
tags:
  - node
  - guides
  - user-friendly
