id: af197ba8-460b-4523-80f4-36b5fe3d54b9
name: La Casa de Satoshi
category: education

links:
  website: https://www.lacasadesatoshi.xyz/
  twitter: https://x.com/LaCasaDeSatoshi
  youtube: https://www.youtube.com/@LaCasaDeSatoshi

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-02-21
    urgency: 1
    contributor_names:
      - jramos0
    reward: 0
tags:
  - DIY
  - software
  - use-case
contributor_names:
  - Asi0Flammeus
