id: 45198444-27c2-4fc1-a761-eb321093642f
name: Electrum
links:
  website: https://electrum.org/#home
  twitter: https://twitter.com/ElectrumWallet
  github: https://github.com/spesmilo/electrum
category: wallet

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.23
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.08
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.2
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.23
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.2
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.3
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.23
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.3
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.27
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.27
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.23

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.23
tags:
  - wallets
  - keys
  - software
