id: 92aa3c6b-deeb-4b50-adf5-92c28eb7a526
name: Get Alby
links:
  website: https://getalby.com/
  twitter: https://twitter.com/getalby
  github: https://github.com/getAlby
  Nostr: npub1getal6ykt05fsz5nqu4uld09nfj3y3qxmv8crys4aeut53unfvlqr80nfm

category: wallet

original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.07
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.22
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.22
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
tags:
  - wallets
  - user-friendly
  - guides
