id: 84e02e9f-e701-4a86-aacf-68d04b079025
name: SatoshiLabs
links:
  website: https://www.satoshilabs.com/
  twitter: https://twitter.com/satoshilabs
  github: https://github.com/trezor

category: wallet

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.26
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.09
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.26
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.34
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.26
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.34
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.3
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.3
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.26

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.26
tags:
  - hardware
  - wallets
  - business
