id: 64f64e0a-7788-46cf-be46-c781b4ec259e
name: Agora256
links:
  website: https://agora256.com
  twitter: https://twitter.com/Agora256
  Nostr: npub1ag0rawstycy7nanuc6sz4v287rneen2yapcq3fd06972f8ncrhzqx7zpqz

category: education

original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.44
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.14
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.36
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.44
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.36
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.62
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.44
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.62
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.53
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.53
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.44

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.44
tags:
  - user-friendly
  - privacy
  - cypherpunk
contributor_names:
  - Rogzy-DB
