id: f77e2e6b-1f62-4020-87db-1d4cd4136d34
name: Bitcoin Berlin SV
category: communities
address_line_1: Berlin, EL Salvador
address_line_2: 2a Calle Poniente, Bitcoin Community Center
address_line_3:
language:
  - en
  -   - es
links:
  twitter: https://twitter.com/BitcoinBerlinSV
  youtube: https://www.youtube.com/@BitcoinBerlinSV

original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.08
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2
tags:
  - legacy
  - historical
  - case-studies
contributor_names:
  - Rogzy-DB
