id: 4c46c260-bc35-4c8c-8cf7-24ec0b2d8688
name: Twilio

links:
  website: https://www.authy.com/
  twitter: https://x.com/twilio

category: infrastructure

# Proofreading metadata
original_language: fr
proofreading:
  - language: fr
    last_contribution_date: 2024-12-11
    urgency: 1
    contributors_id:
      - LoicPandul
    reward: 0.06

  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13

  - language: en
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13

  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14

  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17

  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14

  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13

  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17
tags:
  - software
  - business
  - protocols
