id: 6ecb0909-2c23-4f53-ba30-091135d3f936
name: C=
links:
  website: https://cequals.xyz/
  twitter: https://twitter.com/c_equals

category: infrastructure

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.07
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
tags:
  - legacy
  - deep-dive
  - technical-analysis
