id: 8df1bcbb-0521-4288-b98e-58ec245d5742
name: Nunchuk

links:
  website: https://nunchuk.io/
  twitter: https://x.com/nunchuk_io
  github: https://github.com/nunchuk-io

category: wallet

# Proofreading metadata
original_language: fr
proofreading:
  - language: fr
    last_contribution_date: 2024-12-11
    urgency: 1
    contributor_names:
      - LoicPandul
    reward: 0.07

  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: en
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
tags:
  - wallets
  - keys
  - personal-security
contributor_names:
  - LoicPandul
