id: 79942e25-335d-45ae-bf81-799317f7d6bd
name: Zeus
links:
  website: https://zeusln.app/
  twitter: https://twitter.com/ZeusLN
  github: https://github.com/ZeusLN/zeus
  nostr: npub1xnf02f60r9v0e5kty33a404dm79zr7z2eepyrk5gsq3m7pwvsz2sazlpr5

category: wallet

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.11
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.06
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.11
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.11
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
tags:
  - wallets
  - lightning
  - user-friendly
