id: 8ac2bfcc-7d12-4d9f-b85e-ac03eff327c9
name: Breizh Bitcoin
category: education

links:
  website: https://www.breizhbitcoin.com/
  twitter: https://twitter.com/BreizhBitcoin

original_language: fr
proofreading:
  - language: fr
    last_contribution_date: 2025-01-21
    urgency: 1
    contributors_id:
      - hunt-wood
    reward: 0.07
tags:
  - guides
  - user-friendly
  - market-trends
