id: b3d6dd6d-0cd6-45be-85ba-d6a08c632cd4
name: Mayan Bitcoin
category: education

links:
  twitter: https://x.com/mayanbitcoin

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-20
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.05
tags:
  - historical
  - case-studies
  - adoption
