id: db406c37-93b3-4972-8970-2485752faf24
name: 256 HEAT
category: manufacturer

links:
  website: https://256heat.com/https://256heat.com/

tags:
  - mining
  - hardware
  - self-sovereignty

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-03-07
    urgency: 1
    contributor_names:
      - jramos0
    reward: 0
contributor_names:
  - Rogzy-DB
