id: 24c835b1-26df-45a2-a94b-a92d5911f369
name: Blink
category: wallet

links:
  website: https://www.blink.sv/
  twitter: https://x.com/blinkbtc
  Github: https://github.com/GaloyMoney/blink-mobile
  youtube: done

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-02-18
    urgency: 1
    contributor_names:
      - jramos0
    reward: 0
tags:
  - lightning
  - user-friendly
  - innovation
contributor_names:
  - Asi0Flammeus
