id: 73208946-52c6-43df-a4ca-8275ac770d7d
name: BTCHEL
category: conference

links:
  website: https://btchel.com/
  twitter: https://x.com/btchelevent

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-20
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.06
tags:
  - wallets
  - personal-security
  - keys
