id: 9c8ef98b-a33c-4ccc-8d72-43299a47887b
name: Braiins

links:
  website: https://braiins.com/
  twitter: https://x.com/BraiinsMining

category: mining

# Proofreading metadata
original_language: fr
proofreading:
  - language: fr
    last_contribution_date: 2024-12-11
    urgency: 1
    contributor_names:
      - LoicPandul
    reward: 0.1
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.29

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: en
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.29

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.29

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.34

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.39

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.29

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.29

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.39

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.34
tags:
  - mining
  - software
  - protocols
contributor_names:
  - Asi0Flammeus
