id: 448e0634-3970-4863-8e50-08c658e8374d
name: Blue Wallet
links:
  website: https://bluewallet.io/
  twitter: https://twitter.com/bluewalletio

category: wallet

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.05
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
tags:
  - wallets
  - software
  - user-friendly
contributor_names:
  - Rogzy-DB
