id: 3b824159-a8f2-4eff-95e9-92e37a0dc3d2
name: Bitcoin Medellin
category: conference

links:
  website: https://bitcoinmedellin.com/

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-20
    urgency: 1
    contributors_id:
      - hunt-wood
    reward: 0.05
tags:
  - adoption
  - good-practice
