id: 9891d4f8-e1c3-4156-a1f1-eeaf5ee39e4d
name: Public Pool

links:
  website: https://web.public-pool.io/#/
  twitter: https://x.com/Public_Pool_BTC

category: mining

# Proofreading metadata
original_language: fr
proofreading:
  - language: fr
    last_contribution_date: 2024-12-11
    urgency: 1
    contributor_names:
      - LoicPandul
    reward: 0.08

  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16

  - language: en
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16

  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.26

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.29

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.29

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.26
tags:
  - mining
  - protocols
  - decentralization
