id: b0e42c84-c2c1-4023-959f-ceaa2f343a18
name: Bitcoin Magazine
links:
  website: https://bitcoinmagazine.com/
  twitter: https://twitter.com/BitcoinMagazine

category: news

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.2
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.08
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.2
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.25
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.2
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.25
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.23
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.23
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.2

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.2
tags:
  - historical
  - market-trends
  - legacy
