id: 35af88d4-a734-4471-add4-2190ad1d4a63
name: Entropy
links:
  website: https://entropy.page/pow.html
  twitter: https://x.com/d_plus__plus
  nost: https://primal.net/d++
category: education

original_language: en

proofreading:
  - language: en
    last_contribution_date: 2025-02-04
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.06

  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12

  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14

  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12

  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16

  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14

  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12

  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
tags:
  - keys
  - personal-security
  - good-practice
