id: d3d09b8a-dfbe-4475-921c-589c03953316
name: Amity Age
category: communities
address_line_1: Roatan, Honduras
address_line_2: Calle Principal, Pristine Bay
address_line_3:
language:
  - en
  -   - es
links:
  website: https://www.amityage.com/
  twitter: https://twitter.com/AmityAge
  instagram: https://www.instagram.com/amityage/

original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.08
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
tags:
  - legacy
  - historical
  - cypherpunk
