id: 656c7218-268c-4d5d-bbb4-4b5dea4cb435
name: Bitcoiner Guide
links:
  website: https://bitcoiner.guide
  twitter: https://twitter.com/bitcoinq_a
  github: https://github.com/BitcoinQnA
  Nostr: npub15c88nc8d44gsp4658dnfu5fahswzzu8gaxm5lkuwjud068swdqfspxssvx

category: education

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.07
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.2
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.2
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18
tags:
  - guides
  - self-sovereignty
  - user-friendly
