id: 6f3e50de-f29a-46bf-9328-640188a2e62e
name: TBD
links:
  website: https://www.tbd.website/
  twitter: https://twitter.com/tbd54566975

category: infrastructure

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.07
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
