id: 41814f1c-858b-4d96-9d7a-2ea5e5cd0ecf
name: Wasabi Wallet
links:
  website: https://www.wasabiwallet.io/
  twitter: https://twitter.com/wasabiwallet
  github: https://github.com/zkSNACKs/WalletWasabi

category: wallet

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.09
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.35
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.35
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.31
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.31
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27
tags:
  - wallets
  - privacy
  - good-practice
