id: 120557b9-b1e6-4969-aff4-5bf46fff9869
name: Hodl Hodl
links:
  website: https://hodlhodl.com/
  twitter: https://twitter.com/hodlhodl

category: exchange

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.33
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.22
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.11
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.33
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.22
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.45
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.22
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.33
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.45
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.39
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.39
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.33

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.33
tags:
  - interoperability
  - wallets
  - user-friendly
contributor_names:
  - Rogzy-DB
