id: 6ca330b1-d19c-470e-93a7-98bce38ff0f5
name: Wallet of Satoshi

links:
  website: https://www.walletofsatoshi.com/
  twitter: https://twitter.com/walletofsatoshi
category: wallet

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.11
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.11
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.05
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.11
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.11
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.11
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.11
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.11
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.11
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.11

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.11
tags:
  - wallets
  - lightning
  - user-friendly
