id: f4951074-6937-477c-8944-cabd3b080ac7
name: Arman the parman
links:
  website: https://armantheparman.com
  twitter: https://twitter.com/parman_the
  nostr: npub1ltt9gry09lf2z6396rvzmk2a8wkh3yx5xhgkjzzg5znh62yr53rs0hk97y

category: education

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.07
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.24
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.24
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
tags:
  - good-practice
  - DIY
  - user-friendly
