id: f2c51dbd-d56d-4319-a026-2013833cc23f
name: LNP BP

links:
  website: https://www.lnp-bp.org/
  twitter: https://x.com/lnp_bp

category: infrastructure

# Proofreading metadata
original_language: fr
proofreading:
  - language: fr
    last_contribution_date: 2025-01-17
    urgency: 1
    contributor_names:
      - LoicPandul
    reward: 0.07

  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: en
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
tags:
  - protocols
  - layers
  - development
contributor_names:
  - LoicPandul
