id: eb2caaf0-a74e-40da-918e-7ce56b09ac42
name: Paystand
category: education

links:
  website: https://www.paystand.org/
  twitter: https://x.com/paystand
  youtube: https://www.youtube.com/@paystand-org

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-20
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.06
tags:
  - business
  - finance
  - offchain
contributor_names:
  - PaoloFoti
