id: 0fd3e6cd-7fb6-4429-87d6-b58d5769bbd7
name: Kiveclair
category: communities
address_line_1: Goma, Congo
address_line_2:
address_line_3:
language:
  - fr
  -   - en
links:
  website: https://kiveclair.com/
  twitter: https://twitter.com/kiveclair
  youtube: https://www.youtube.com/channel/UCjckvkmrZ-2mxW9fQpQJzvw

original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.08
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.26
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.26
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
tags:
  - hardware
  - node
  - DIY
