id: b731a421-7e83-44e9-8f2b-f4a51f7a08e2
name: Fulgur Ventures
links:
  website: https://fulgur.ventures/
  twitter: https://twitter.com/fulgurventures

category: investment

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.07
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
tags:
  - investment
  - business
  - market-trends
contributor_names:
  - Rogzy-DB
