id: ae940910-85f8-4a82-b779-d5eb3c5a30ba
name: Nodl
links:
  website: https://www.nodl.eu/
  twitter: https://twitter.com/nodl_it

category: node

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.08
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.28
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.28
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.25
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.25
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22
tags:
  - node
  - hardware
  - guides
