id: fdefd30e-ebd0-47c5-80a3-1c0f37102d96
name: European Bitcoiners
links:
  twitter: https://twitter.com/EuropeanBTC21
  website: https://europeanbitcoiners.com/

category: news

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.09
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.32
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.32
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.28
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.28
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25
tags:
  - decentralization
  - self-sovereignty
  - user-friendly
contributor_names:
  - Rogzy-DB
