id: 0759d753-b6a3-4038-9eea-4dcdc8f09c79
name: Swan
links:
  website: https://www.swanbitcoin.com/
  twitter: https://twitter.com/swanbitcoin

category: exchange

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.06
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
tags:
  - market-trends
  - investment
  - finance
contributor_names:
  - Rogzy-DB
