id: 326fd972-4807-4f01-974d-f8bfa9bfee6a
name: Watch Out Bitcoin
category: conference

links:
  website: https://wobitcoin.org
  twitter: https://x.com/Wo_Bitcoin
  youtube: https://www.youtube.com/@WOBitcoin

original_language: es
proofreading:
  - language: es
    last_contribution_date: 2025-01-13
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.06
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: en
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
tags:
  - privacy
  - personal-security
  - good-practice
