id: 05f0c068-36a9-45b7-bafa-b7490d141b74
name: Bitcoin Filmfest
category: conference

links:
  website: https://bitcoinfilmfest.com/
  twitter: https://twitter.com/bitcoinfilmfest

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-20
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.08
tags:
  - innovation
  - user-friendly
  - adoption
