id: d655e18b-d299-4c88-beb5-e6b688d86024
name: Proton

links:
  website: https://proton.me/
  twitter: https://x.com/ProtonPrivacy

category: privacy

# Proofreading metadata
original_language: fr
proofreading:
  - language: fr
    last_contribution_date: 2024-12-11
    urgency: 1
    contributor_names:
      - LoicPandul
    reward: 0.08

  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: en
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.26

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.26

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23
tags:
  - DIY
  - personal-security
  - guides
