id: 66809911-775f-44ed-a5bb-dedb2649d7d7
name: Bitcoin Beach
category: communities
address_line_1: El Zonte, El Salvador
address_line_2:
address_line_3:
language:
  - en
  - es
links:
  twitter: https://x.com/Bitcoinbeach
  youtube: https://www.youtube.com/channel/UCOT9XfrKaiKunSGYSQNmRrg
  github: https://github.com/bitcoinbeach/

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2024-08-31
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.07

  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19

  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
tags:
  - adoption
  - use-case
  - business
contributor_names:
  - Rogzy-DB
