id: 615f613f-2d57-4ce3-83c0-baf6f87f7c9b
name: OesteBitcoin
category: conference

links:
  website: 
    https://primal.net/p/npub1va4vvlyfwnqss496f3dc4rsa4gtpfdx6crr8ppp8sz82uf9fczxq4wda00

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-20
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.05
tags:
  - guides
  - decentralization
