id: 7932b607-1c7d-4180-834f-1f90a775e093
name: Bitcoin Tokyo
category: conference

links:
  website: https://bitcoinconference.tokyo/
  twitter: https://x.com/BTCTokyo2024

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2024-12-17
    urgency: 1
    contributor_names:
      - jramos0
    reward: 0.06

  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
tags:
  - future-outlook
  - adoption
  - market-trends
