id: a1be43bf-7229-4021-bb15-8f6d97ef003c
name: KeePass

links:
  website: https://keepass.info/
  twitter: https://x.com/keepass

category: privacy

# Proofreading metadata
original_language: fr
proofreading:
  - language: fr
    last_contribution_date: 2024-12-11
    urgency: 1
    contributor_names:
      - LoicPandul
    reward: 0.07

  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: en
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
tags:
  - good-practice
  - keys
  - personal-security
contributor_names:
  - LoicPandul
