id: ccaacfff-12c3-4b5c-80f8-0f077422d62b
name: Galoy
links:
  website: https://galoy.io/
  twitter: https://twitter.com/GaloyMoney
  github: https://github.com/GaloyMoney
category: infrastructure

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.31
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.1
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.26
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.31
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.26
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.42
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.31
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.42
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.36
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.36
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.31

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.31
tags:
  - business
  - software
  - wallets
contributor_names:
  - Rogzy-DB
