id: 21dd7c32-3fba-463e-915d-78a3da832941
name: Bitcoin is for Everyone
category: conference

links:
  website: https://bitcoinisforeveryone.com
  twitter: https://twitter.com/BITCOINisforALL

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-20
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.07
tags:
  - user-friendly
  - adoption
  - self-sovereignty
contributor_names:
  - PaoloFoti
