id: ce82f356-4662-4dad-ba0c-a0ec4f56cf2a
name: GrapheneOS

links:
  website: https://grapheneos.org/
  twitter: https://x.com/GrapheneOS

category: privacy

# Proofreading metadata
original_language: fr
proofreading:
  - language: fr
    last_contribution_date: 2024-12-11
    urgency: 1
    contributor_names:
      - LoicPandul
    reward: 0.08

  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: en
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.26

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.26

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23
tags:
  - personal-security
  - software
  - good-practice
