id: 0f5cd09e-135a-4cb6-bee9-241695dba785
name: Captain Sidd
category: service

links:
  website: https://www.rideofpassage.live/
  twitter: https://x.com/CaptainSidd

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-20
    urgency: 1
    contributors_id:
      - hunt-wood
    reward: 0.07
tags:
  - cypherpunk
  - self-sovereignty
  - personal-security
