id: a60dfea6-0210-4208-bbba-c04914e285f6
name: LNbits
links:
  website: https://lnbits.com/
  twitter: https://twitter.com/lnbits
  github: https://github.com/GaloyMoney

category: wallet

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.4
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.12
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.32
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.4
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.32
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.55
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.4
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.55
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.47
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.47
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.4

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.4
tags:
  - lightning
  - wallets
  - user-friendly
