id: 71778fff-448f-4acb-974c-9fb3cec1885e
name: Imperia Online JSC
category: service

links:
  website: https://www.imperiaonline.org/imperia/game_v6/game/frontpage.php?games=ok&ref=

tags:
  - use-case
  - software
  - innovation

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-02-17
    urgency: 1
    contributors_id:
      - jramos0
    reward: 0