id: 3ad86f15-94ef-401c-b708-b28c7767b9be
name: Bitfinex
links:
  website: https://www.bitfinex.com/
  twitter: https://twitter.com/bitfinex

category: exchange

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.09
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.31
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.31
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.28
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.28
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
tags:
  - software
  - wallets
  - business
