id: 4592bee1-51a0-45ce-b6ea-deb42da6aaad
name: Phneep
category: education

links:
  website: https://phneep.com/
  twitter: https://x.com/phneep

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2024-12-10
    urgency: 1
    contributors_id:
      - jramos0
    reward: 0.07

  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17

  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14

  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17

  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17

  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14

  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19

  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17

  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14

  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17

  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
tags:
  - hardware
  - DIY
  - guides
