id: db7cc106-432c-4571-a66a-1f68d024bca4
name: Lightning Labs
links:
  website: https://lightning.engineering/
  twitter: https://twitter.com/lightning
  github: https://github.com/lightningnetwork/lnd
category: infrastructure

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.09
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.22
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.22
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.33
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.33
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.29
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.29
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25
tags:
  - lightning
  - business
  - development
contributor_names:
  - Rogzy-DB
