id: c0cf9fca-a0c4-4418-a85d-696d2c84a548
name: PlanB Network Taipei
category: communities
address_city_country: Taipei, Taiwan
address_line_2:
address_line_3:
language:
  - zh-tw
  - en
links:
  twitter: https://x.com/PlanBTaiwanNode

original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.07
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
tags:
  - decentralization
  - privacy
  - network-security
contributor_names:
  - Rogzy-DB
