id: 5c2f09e3-e6ce-4751-8ba6-27bfc1ba14a3
name: Umbrel
links:
  website: https://umbrel.com/
  twitter: https://twitter.com/umbrel
  github: https://github.com/getumbrel/umbrel

category: node

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.07
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.22
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.22
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2
tags:
  - node
  - DIY
  - user-friendly
contributor_names:
  - Rogzy-DB
