id: b17efc14-aaa4-449a-a666-1f7db084a922
name: Bull Bitcoin
links:
  website: https://www.bullbitcoin.com/
  twitter: https://twitter.com/BullBitcoin_
  github: https://github.com/SatoshiPortal/cyphernode
category: exchange

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.09
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.31
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.31
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.28
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.28
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
tags:
  - business
  - wallets
  - user-friendly
