id: deee5178-a3e8-4697-b72e-2e7e36906a9c
name: LNVPN
links:
  website: https://lnvpn.net/
  twitter: https://twitter.com/ln_vpn

category: privacy

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.07
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
tags:
  - privacy
  - software
  - user-friendly
contributor_names:
  - Rogzy-DB
