id: 54e06b86-9b5e-4134-88e8-af304e8aa22b
name: Unconfiscatable
category: conference

links:
  website: https://unconfiscatable.com/
  twitter: https://x.com/unconfiscatable
  youtube: https://www.youtube.com/@unconfiscatable

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-19
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.05
tags:
  - personal-security
  - keys
  - self-sovereignty
