id: 4595235a-f943-4976-9c16-0518dd372511
name: Trezor
links:
  website: https://trezor.io/
  twitter: https://twitter.com/Trezor
  github: https://github.com/trezor

category: wallet

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.06
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
tags:
  - wallets
  - hardware
  - keys
