id: f6ddbf31-fdf8-457f-a5c5-90d009ed9c62
name: TimechainStats
links:
  website: https://timechainstats.com/
  twitter: https://twitter.com/TimechainStats

category: infrastructure

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.06
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
tags:
  - historical
  - market-trends
