id: 381b50a1-232c-4170-922d-2943d840a567
name: Wolf
category: investment

links:
  website: https://wolfnyc.com
  twitter: https://x.com/_WolfNYC

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-21
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.07
tags:
  - case-studies
  - business
  - evaluation
