id: a0bae034-16f0-4da0-9fb7-39d664347672
name: CheatCode
category: conference

links:
  website: https://www.cheatcode.co.uk/
  twitter: https://twitter.com/CheatCodeCon
  youtube: https://www.youtube.com/channel/UCRfYoKkmvWWTj6M092WnvPg

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-20
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.06
tags:
  - guides
  - good-practice
  - user-friendly
contributor_names:
  - PaoloFoti
