id: b5ad8fa7-8571-4421-a5d0-8eff5b3eab6b
name: EINUNDZWANZIG
category: education

links:
  website: https://einundzwanzig.space
  twitter: https://twitter.com/_einundzwanzig_
  youtube: https://www.youtube.com/c/EinundzwanzigPodcast

original_language: de
proofreading:
  - language: de
    last_contribution_date: 2025-01-20
    urgency: 1
    contributors_id:
      - hunt-wood
    reward: 0.06
tags:
  - guides
  - easy-explain
  - user-friendly
