id: f2081124-af3b-49ec-a299-f6146d24835c
name: Mondo Convenienza
category: merchant

links:
  website: https://www.mondoconv.it/

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-02-17
    urgency: 1
    contributor_names:
      - jramos0
    reward: 0
tags:
  - evaluation
  - case-studies
  - business
