id: db0f0b26-3fd8-4d3b-94cc-1f55f30fe768
name: Africa Bitcoin Conference
category: conference

links:
  website: https://afrobitcoin.org
  twitter: https://twitter.com/AfroBitcoinOrg
  youtube: https://www.youtube.com/@africabitcoinconference

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-13
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.09
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18

  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27

  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.31

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.35

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.35

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.31
tags:
  - adoption
  - decentralization
  - market-trends
