id: 2b915c00-50b6-4420-bb8b-15e891062130
name: Ocean

links:
  website: https://ocean.xyz/
  twitter: https://x.com/ocean_mining

category: mining

# Proofreading metadata
original_language: fr
proofreading:
  - language: fr
    last_contribution_date: 2024-12-11
    urgency: 1
    contributor_names:
      - LoicPandul
    reward: 0.07

  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: en
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2
tags:
  - smart-contracts
  - interoperability
  - sidechains
