id: 28dd0137-b167-4e74-bc43-a5df60b93c00
name: JAN3

links:
  website: https://jan3.com/
  twitter: https://x.com/JAN3com

category: infrastructure

# Proofreading metadata
original_language: fr
proofreading:
  - language: fr
    last_contribution_date: 2024-12-12
    urgency: 1
    contributors_id:
      - LoicPandul
    reward: 0.07

  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19

  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: en
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17

  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19

  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19

  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22

  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17

  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.24

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19

  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19

  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.24

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22
tags:
  - business
  - technical-analysis
  - evaluation
