id: 6d6cedde-3ba0-4eaa-b539-676132a89d27
name: Barcelona Cyphers Conference
category: conference

links:
  website: https://tickets.bcc8333.com/
  twitter: https://x.com/bcc8333

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-02-26
    urgency: 1
    contributor_names:
      - jramos0
    reward: 0
tags:
  - cypherpunk
  - self-sovereignty
  - privacy
