id: 6d83d316-c513-4795-824a-26bf4687b0b8
name: Zum Wilden Michel Farm
category: conference

links:
  website: https://www.zumwildenmichel.de

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-29
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.11
tags:
  - business
  - use-case
  - adoption
