id: a3d80e75-8ea0-4133-807a-27578d5c62a5
name: Israeli Bitcoin Association
category: education

links:
  website: https://bitcoin.org.il
  youtube: https://www.youtube.com/channel/UC58YJLWM7hsKUZOQtmAHcvQ

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-13
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.07

  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.22

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.22
tags:
  - business
  - adoption
  - user-friendly
