id: eef8c3d4-2ec8-4f8d-9fd5-b146191ae52d
name: Breaking Bitcoin
links:
  website: https://breaking-bitcoin.com/
  twitter: https://twitter.com/breakingbitcoin

category: conference

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.07
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
tags:
  - historical
  - cypherpunk
contributor_names:
  - Asi0Flammeus
