id: 57b02b5e-90a3-4b1a-aacd-67785326d267
name: Only One TV
category: conference

links:
  youtube: https://www.youtube.com/@vlogwrap

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-17
    urgency: 1
    contributors_id:
      - hunt-wood
    reward: 0.05
tags:
  - high-level
  - easy-explain
