id: b35f4cff-c9fd-4e51-8771-ed1b4d3184fd
name: PlebLab
category: communities
address_city_country: Austin, Texas
address_line_2:
address_line_3:
language:
  - en
links:
  website: https://www.pleblab.com/
  twitter: https://twitter.com/PlebLab
  github: https://www.github.com/PlebLab
  youtube: https://www.youtube.com/channel/UCoUUXOdWNOSv_MTtYXMUwDA
  nostr: 
    https://primal.net/profile/npub1an84q6c03wml5lf0uwcqcr20ydwv0t0lvv0xktlcfs9seattef8sdhz6yg

original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.07
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
tags:
  - mining
  - DIY
  - hardware
contributor_names:
  - Rogzy-DB
