id: a619c7ac-9adb-481e-93e2-62a11c8fe2e0
name: Kraken
links:
  website: https://www.kraken.com/
  twitter: https://twitter.com/krakenfx

category: exchange

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.06
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
tags:
  - wallets
  - business
  - market-trends
