id: ede0df1a-9406-4f8e-949f-86c3dd2e87fb
name: Area Bitcoin
links:
  website: https://www.areabitcoin.co/
  twitter: https://x.com/areabitcoin
  nost: 
    https://primal.net/p/npub13zpemj05wvgadhgyyv4e0captmkd64p8kz323pfq87ffahrws0ms9yp5ww
category: education

original_language: en

proofreading:
  - language: en
    last_contribution_date: 2025-02-04
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.06

  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
tags:
  - decentralization
  - network-security
