id: 839be5ad-132d-469e-8ba6-143b56987461
name: El Salvador's Plan ₿
category: conference

links:
  website: https://planb.sv/
  twitter: https://x.com/PlanBElsalvador
  youtube: 
    https://youtube.com/playlist?list=PLNETuT4LKydIXpVYuVxJYsjtcDKJeilIe&si=iqqcOUA6t2uJisLC

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-19
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.06
tags:
  - adoption
  - regulation
