id: 07d415f7-c302-4eb8-a67d-79d9f4633732
name: Bitcoin4India
category: communities
address_city_country:
address_line_2:
address_line_3: Mumbai, India
language:
  - en

links:
  website: https://bitcoin4india.org/
  twitter: https://twitter.com/Bitcoin4India

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-13
    urgency: 1
    contributors_id:
      - hunt-wood
    reward: 0.06

  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14

  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12

  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13

  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14

  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14

  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12

  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16

  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13

  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14

  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12

  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14

  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
tags:
  - adoption
  - user-friendly
  - future-outlook
