id: fd05debc-391c-4a3a-a3ea-0d9604c52a72
name: Learn me a Bitcoin

links:
  website: https://learnmeabitcoin.com/
  twitter: https://twitter.com/in3rsha
  github: https://github.com/in3rsha

category: education

original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.09
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.36
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.36
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.32
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.32
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27
tags:
  - user-friendly
  - guides
  - easy-explain
