id: 41c4621e-7411-42a8-9ef9-90c29e19b76a
name: Breez
links:
  website: https://breez.technology/
  twitter: https://twitter.com/Breez_Tech
  github: https://github.com/breez/breezmobile
category: wallet

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.28
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.1
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.28
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.37
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.28
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.37
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.32
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.32
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.28

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.28
tags:
  - wallets
  - lightning
  - user-friendly
