id: d9bc9f7f-7290-4a3b-b2ca-9745c7d6063c
name: Mullvad

links:
  website: https://mullvad.net/
  twitter: https://x.com/mullvadnet

category: privacy

# Proofreading metadata
original_language: fr
proofreading:
  - language: fr
    last_contribution_date: 2024-12-11
    urgency: 1
    contributors_id:
      - LoicPandul
    reward: 0.08

  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21

  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16

  - language: en
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16

  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18

  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21

  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21

  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.24

  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18

  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.27

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21

  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16

  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21

  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.27

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.24
tags:
  - privacy
  - network-security
  - user-friendly
