id: d8900764-9481-495f-9219-01d6cbf9d5ea
name: London BTC Meetup
category: education

links:
  website: https://www.meetup.com/LondonBitcoin/
  twitter: https://x.com/londonON_BTC

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-20
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.06
tags:
  - adoption
  - use-case
  - business
