id: 3833a0e2-4fac-4832-8e7c-487f736d24cd
name: ZEBEDEE
links:
  website: https://zebedee.io/
  twitter: https://twitter.com/zebedeeio
  github: https://github.com/ln-markets
  Nostr: npub1lnm0ac8ft8r3jhddchekledgwvqrkwy7wqejjwcxq47gy87te8zs6utnnn
category: infrastructure

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.08
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.27
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
tags:
  - wallets
  - software
  - user-friendly
