## Community Builder Characteristic

# Complete name of the builder
name: Community Builder Complete name

# Define Builder category
# Can only be communities
category: communities

# Define Builder address
# line 1 for more precise, name of the place
address_city_country: PBN HQ
# line 2 for the steet name
address_line_2: 21st Satoshi's Place
# line 3 for the City, Country
address_line_3: CyberTown, CyberSpace

# Community Language
# Define the spoken language of the community
# format: use code langugage (see https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
language:
  - en
  - es

# links
# list releated online presence like twitter and/or website
links:
  website: https://stackharder.com
  twitter: https://twitter.com/stackharder
  Github: https://github.com/DecouvreBitcoin/sovereign-university-data
  youtube: https://www.youtube.com/@PlanBNetwork

# tags
# List the associated tags to the author
# The list of tags is composed of 21 items that can be found here (list not yet available)
tags:
  - finance
  - education
