id: d0db0105-c5ea-4d2c-9559-80be9246d935
name: Nostr.World
category: conference

links:
  website: https://nostr.world/index.html

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-20
    urgency: 1
    contributors_id:
      - hunt-wood
    reward: 0.06
tags:
  - protocols
  - software
  - decentralization
