id: 9a5bbbc3-22ac-4c98-b10a-c953f9fae337
name: Bisq
links:
  website: https://bisq.network/
  twitter: https://twitter.com/bisq_network

category: exchange

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.06
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
tags:
  - decentralization
  - software
  - privacy
