id: 0726adb9-4d45-4e5c-af2c-0a26db29d9b3
name: BTCprague
links:
  website: https://2024.btcprague.com/
  twitter: https://twitter.com/BtcPrague
  nostr: npub167n5w6cj2wseqtmk26zllc7n28uv9c4vw28k2kht206vnghe5a7stgzu3r
  youtube: https://www.youtube.com/@BTCPrague

category: conference

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.07
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.22
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.22

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
tags:
  - historical
  - innovation
  - business
contributor_names:
  - Rogzy-DB
  - Asi0Flammeus
