id: a6eb4a7b-edc2-4ba4-9237-0db8ff0ef769
name: Rigly
links:
  website: https://auctions.rigly.io/
  twitter: https://twitter.com/TrustlessMining
  nostr: npub1t6el40knsq8hmrpr0m6tt3t0tr4pdeyhlt2qelwhgtwawddqx0xsv03scu

category: mining

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.07
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.21
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
tags:
  - protocols
  - smart-contracts
  - protocols
contributor_names:
  - Rogzy-DB
