id: b1dcf2e8-81b0-4286-9e44-bb97a526ef69
name: Bitcoin Core

links:
  website: https://bitcoincore.org/
  twitter: https://x.com/bitcoincoreorg

category: infrastructure

# Proofreading metadata
original_language: fr
proofreading:
  - language: fr
    last_contribution_date: 2024-12-11
    urgency: 1
    contributors_id:
      - LoicPandul
    reward: 0.09

  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.26

  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18

  - language: en
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18

  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22

  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.26

  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.26

  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.31

  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22

  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.35

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.26

  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18

  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.26

  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.35

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.31
tags:
  - node
  - software
  - protocols
