id: 4370ef85-a176-45ff-af8f-0c9e8eaf6939
name: BitDevs El Salvador
category: education

links:
  website: https://bitdevelsalvador.com/
  Github: https://github.com/nicolasburtey/bitdev-el-salvador.github.io

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-20
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.06
tags:
  - development
  - software
  - case-studies
