id: 8d4b2973-eaa2-4954-9da6-24d620e12e7f
name: Bitcare Forum
category: conference

links:
  website: https://bitcareforum.it/
  twitter: https://x.com/BitcareForum
  youtube: https://www.youtube.com/@bitcareforum

original_language: it
proofreading:
  - language: it
    last_contribution_date: 2024-12-16
    urgency: 1
    contributors_id:
      - jramos0
    reward: 0.06

  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13

  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12

  - language: en
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12

  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12

  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13

  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13

  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12

  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14

  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13

  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12

  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13

  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14
tags:
  - software
  - wallets
  - user-friendly
