id: 77d117fc-a2b1-4e2c-8442-ea00ff8cf70a
name: The Bitcoin Conference
category: conference

links:
  website: https://b.tc/conference/
  twitter: https://x.com/TheBitcoinConf

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2024-12-10
    urgency: 1
    contributor_names:
      - jramos0
    reward: 0.05

  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11

  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
tags:
  - adoption
  - case-studies
  - business
contributor_names:
  - Rogzy-DB
