id: d7104dab-21a5-4911-983c-ca049497ee72
name: The School of Bitcoin
category: communities
address_line_1: Melbourne, Australia
address_line_2:
address_line_3:
language:
  - en
links:
  website: https://theschoolofbitcoin.com/
  github: https://v4v.theschoolofbitcoin.com/
  nostr: https://nosta.me/npub19p345mfx9cdks8a7p5vzyt9vkhavueh7g57murk24mwa0mn08fes8wdkan

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2024-08-31
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.08

  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21

  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18

  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21

  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21

  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.24

  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18

  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.26

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21

  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15

  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21

  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.26

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.24
tags:
  - guides
  - user-friendly
