id: 0fbcc87c-3be1-4e2f-8f3f-5116db036d32
name: Nerd Miners

links:
  website: https://nerdminers.com/
  twitter: https://x.com/nerdminers

category: mining

# Proofreading metadata
original_language: fr
proofreading:
  - language: fr
    last_contribution_date: 2024-12-11
    urgency: 1
    contributor_names:
      - LoicPandul
    reward: 0.07

  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: en
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.22

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.24

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.22
tags:
  - mining
  - technical-analysis
  - hardware
