id: 443e805b-6f15-4b89-8f6b-100f4ee2e767
name: Bitcoin Bristol
category: education

links:
  website: https://bitcoinbristol.org/
  twitter: https://x.com/BitcoinBRS

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-20
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.07
tags:
  - user-friendly
  - adoption
  - guides
contributor_names:
  - PaoloFoti
