id: 740c3162-12a9-49df-a847-f628119ea45d
name: Voltage
links:
  website: https://voltage.cloud/
  twitter: https://twitter.com/voltage_cloud

category: infrastructure

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.08
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.18
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.27
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.27
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.24
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.24
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21
tags:
  - node
  - software
  - user-friendly
