id: 5e8b6610-44b7-4a69-be02-a5c62187dd02
name: Baltic HoneyBadger
links:
  website: https://baltichoneybadger.com/

category: conference

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.05
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11
tags:
  - historical
  - case-studies
  - cypherpunk
contributor_names:
  - Rogzy-DB
