id: ea84df86-4dfe-48fa-a763-3e414ce7c791
name: Speed Wallet
links:
  website: https://www.speed.app/
  twitter: https://x.com/speedwallet
category: wallet

original_language: en

proofreading:
  - language: en
    last_contribution_date: 2025-02-04
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.07
tags:
  - wallets
  - user-friendly
  - software
contributor_names:
  - Rogzy-DB
