id: 8a053a83-22a4-4d61-8a8b-26f3ae74b9c1
name: Swiss Bitcoin Pay
links:
  website: https://swiss-bitcoin-pay.ch/
  twitter: https://twitter.com/SwissBitcoinPay

category: infrastructure

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.11
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.06
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.11
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.11
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
tags:
  - adoption
  - fees
  - user-friendly
