id: 93f297d8-5cbc-4421-b8d5-2d1bff66592e
name: The Bitcoin Backup
links:
  website: https://www.thebitcoinbackup.com/
  twitter: https://twitter.com/TheBTCBackup

category: education

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.06
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
tags:
  - backup
  - guides
  - good-practice
contributor_names:
  - Rogzy-DB
  - Asi0Flammeus
