id: c6d6561c-3069-4029-82a4-979cf862a138
name: Namecheap
category: service

links:
  website: https://www.namecheap.com/
  twitter: https://x.com/namecheap

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-02-17
    urgency: 1
    contributors_id:
      - jramos0
    reward: 0
tags:
  - business
  - finance
  - guides
