id: 04f42f7c-2ecd-409f-badc-338855b3b433
name: The Bitcoin Company
links:
  website: https://thebitcoincompany.com
  twitter: https://twitter.com/thebtcco
  nostr: npub18tcc00lqpysdsurg567dllzg7jeyr5wcyk2v6w23rx3s3ygyze2qv32nxx

category: service

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.07
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.23
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.23
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
tags:
  - business
  - adoption
  - user-friendly
