id: b2cdb3d7-9f8a-4452-8715-dc91bac82345
name: ₿itcoin Sénégal
category: conference

links:
  twitter: https://x.com/bitcoin_sen
  youtube: https://www.youtube.com/channel/UCsKRlUJFd29M2ouZm7zdMkQ

original_language: fr
proofreading:
  - language: fr
    last_contribution_date: 2025-01-13
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.06
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: en
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
tags:
  - guides
  - adoption
  - user-friendly
