id: 53774b9c-1612-4e86-990c-221a7034b998
name: Bitvavo
category: exchange

links:
  website: https://bitvavo.com
  twitter: https://x.com/bitvavocom

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2025-01-13
    urgency: 1
    contributor_names:
      - hunt-wood
    reward: 0.06
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
tags:
  - business
  - wallets
  - user-friendly
contributor_names:
  - PaoloFoti
