id: 51ad9786-d4f5-4f72-83f8-7146405ba443
name: O$mo Wallet
category: wallet

links:
  website: https://en.osmowallet.com/
  twitter: https://x.com/osmowallet

original_language: es
proofreading:
  - language: es
    last_contribution_date: 2025-02-17
    urgency: 1
    contributor_names:
      - jramos0
    reward: 0
tags:
  - wallets
  - smart-contracts
  - user-friendly
contributor_names:
  - Asi0Flammeus
