id: 0c4e77ed-11bf-4d93-94cb-9d061caabf69
name: Coincorner
links:
  website: https://www.coincorner.com
  twitter: https://twitter.com/CoinCorner

category: exchange

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.32
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.1
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.26
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.32
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.26
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.43
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.32
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.43
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.37
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.37
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.32

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.32
tags:
  - business
  - wallets
  - adoption
