id: 10e85d67-c568-462a-b918-a35e2491b450
name: CUBO+
category: communities
address_city_country: San Salvador, El Salvador
address_line_2:
address_line_3:
language:
  - en
  -   - es
links:
  website: https://www.cuboplus.academy/
  twitter: https://x.com/cuboplus?t=qXP3Sckahhzw-Y_5sSGoxA&s=09
  youtube: https://www.youtube.com/@cuboplus
  instagram: https://www.instagram.com/cubo_plus/

original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.28
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.1
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.24
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.28
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.24
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.38
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.28
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.38
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.33
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.33
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.28

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.28
tags:
  - hardware
  - DIY
  - guides
