id: fd832594-924b-4fc0-a7b6-6a400aed3033
name: Bitcoin Foundation
links:
  website: https://www.bitcoinfoundation.org/
  twitter: https://twitter.com/btcfoundation

category: education

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.06
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14
tags:
  - historical
  - adoption
  - business
