id: aa91f010-ea13-44f1-ac91-d3f02aea8f21
name: Wizard Sardine
links:
  website: https://wizardsardine.com/
  twitter: https://twitter.com/wizardsardine
  github: https://github.com/wizardsardine

category: wallet

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.08
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.27
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.27
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.25
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.25
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.22
tags:
  - DIY
  - hardware
  - guides
