id: 920df8e3-9c13-43f6-a84a-ac786e56b893
name: 4NK Academy
category: communities
address_line_1: Bois-Guillaume, Rouen, France
address_line_2: 75 allée Paul Langevin 76230 Bois-Guillaume
address_line_3:
language:
  - fr

links:
  website: https://4nk.academy/
  twitter: https://x.com/4NKACADEMY

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2024-12-02
    urgency: 1
    contributors_id:
      - another-satoshi
    reward: 0.09

  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.25

  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17

  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21

  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.25

  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.25

  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17

  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.29

  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.21

  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.32

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.25

  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17

  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.25

  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.32

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.29
tags:
  - guides
  - user-friendly
  - good-practice
