id: 3ece7cc0-6893-4ace-ba4a-a015c2c382d1
name: Adopting Bitcoin
category: conference

links:
  website: https://www.adoptingbitcoin.org/
  twitter: https://x.com/AdoptingBTC

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2024-12-17
    urgency: 1
    contributor_names:
      - jramos0
    reward: 0.06

  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.17
tags:
  - adoption
  - use-case
  - user-friendly
contributor_names:
  - Rogzy-DB
