id: d0112afe-ce46-4ef2-9cca-f352ea9c46cf
name: Linux Mint
links:
  website: https://www.linuxmint.com/
  twitter: https://twitter.com/linux_mint

category: privacy

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.06
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.12
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.16
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.14
tags:
  - software
  - DIY
  - user-friendly
