id: 1ccbbeae-ef92-4128-ad85-24f29e1759ca
name: TABConf
category: conference

links:
  website: https://6.tabconf.com/
  twitter: https://x.com/tabconf

original_language: en
proofreading:
  - language: en
    last_contribution_date: 2024-12-10
    urgency: 1
    contributor_names:
      - jramos0
    reward: 0.06

  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11

  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11

  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.12

  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.11

  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13

  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14

  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.14
tags:
  - guides
  - development
  - user-friendly
