id: a465ba43-cec3-449d-95ed-4b06780e0510
name: IVPN
links:
  website: https://www.ivpn.net/
  twitter: https://twitter.com/ivpnnet
  github: https://github.com/ivpn

category: privacy

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.36
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.11
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.29
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.36
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.29
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.49
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.23
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.36
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.49
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.42
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.42
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.36

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.36
tags:
  - privacy
  - network-security
  - software
contributor_names:
  - Rogzy-DB
