id: 5cffb254-278e-4d87-a4d6-4efe5a538dde
name: Bitshala
category: communities
address_line_1: Bangalore, India
address_line_2:
address_line_3:
language:
  - en
links:
  website: https://www.bitshala.org
  twitter: https://twitter.com/bitshala_org
  nostr: npub1m495fdq2e8jleptdq6ruzpmz0esjttln2rjx7dxj9w4zvxs48y3q5pu22l

original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.29
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.1
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.29
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.25
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.39
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.2
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.29
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.39
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.34
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.34
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.29

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.29
tags:
  - software
  - guides
  - user-friendly
contributor_names:
  - Rogzy-DB
