id: 77bf59df-9e3e-4b85-a695-81076a44c14a
name: AgoraDesk
links:
  website: https://twitter.com/AgoraDesk
  twitter: https://github.com/AgoraDesk-LocalMonero
  github: https://agoradesk.com/

category: exchange
# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: de
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.07
  - language: es
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: fi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: fr
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: it
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.15
  - language: ja
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: pt
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.13
  - language: ru
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
  - language: vi
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.19
  - language: id
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.18
  - language: et
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributor_names:
    reward: 0.16
tags:
  - software
  - wallets
