id: 21e68928-68a3-468f-9c18-2b25a045c540
name: Ledger
links:
  website: https://www.ledger.com/
  twitter: https://twitter.com/Ledger
  github: https://github.com/LedgerHQ

category: wallet

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.24
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.08
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.2
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.24
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.2
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.3
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.24
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.3
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.27
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.27
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.24

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.24
tags:
  - hardware
  - keys
  - wallets
