id: 42c9f6cd-9167-4cce-bd5d-7902f2fb63a8
name: Bolt Fun
links:
  website: https://makers.bolt.fun/feed
  twitter: https://twitter.com/boltfun_btc

category: education

# Proofreading metadata
original_language: en
proofreading:
  - language: cs
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17
  - language: de
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: en
    last_contribution_date: 2024-09-01
    urgency: 1
    contributors_id:
      - Asi0Flammeus
    reward: 0.07
  - language: es
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15
  - language: fi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17
  - language: fr
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: it
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.15
  - language: ja
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.2
  - language: pt
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.13
  - language: ru
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17
  - language: vi
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.2
  - language: id
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
  - language: zh-Hans
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.19
  - language: et
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17

  - language: nb-NO
    last_contribution_date:
    urgency: 1
    contributors_id:
    reward: 0.17
tags:
  - lightning
  - development
  - user-friendly
